#!/bin/bash
# Reproduce the pinned device-only runtime. Never touches a phone or model weights.
# Failure cases: existing/symlink output, changed archive, missing dependency/license,
# configure/build failure or missing library. Preserve failures; no automatic retry.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD/.build/firered-runtime"
[ ! -e "$ROOT" ] && [ ! -L "$ROOT" ] || { echo "STOP: $ROOT already exists; preserve and review it before rebuilding." >&2; exit 1; }
[ ! -L .build ] || { echo "STOP: .build must be checkout-owned, not a symlink." >&2; exit 1; }
mkdir -p .build
mkdir "$ROOT"
export ROOT
SOURCE_SHA=e687d9cc9b490148a6aa266621f1e0254287e737ddd71ac771a24e03dc140a84
ORT_SHA=2c2299acbb461d26d4bac4bc85985d40e7c7177ed6072703ae0846d88b0b4599
curl --fail --location --max-time 120 --output "$ROOT/sherpa-source.tar.gz" \
  https://api.github.com/repos/k2-fsa/sherpa-onnx/tarball/a5b4a944c5186a68bcdc0ac3011e4c541781ac84
printf '%s  %s\n' "$SOURCE_SHA" "$ROOT/sherpa-source.tar.gz" | shasum -a 256 -c -
curl --fail --location --max-time 120 --output "$ROOT/ort-ios.zip" \
  https://github.com/csukuangfj/onnxruntime-libs/releases/download/v1.28.2/onnxruntime-ios-static-xcframework-1.28.2.xcframework.zip
printf '%s  %s\n' "$ORT_SHA" "$ROOT/ort-ios.zip" | shasum -a 256 -c -
mkdir "$ROOT/sherpa-onnx" "$ROOT/ort-ios"
tar -xzf "$ROOT/sherpa-source.tar.gz" -C "$ROOT/sherpa-onnx" --strip-components=1
unzip -q "$ROOT/ort-ios.zip" -d "$ROOT/ort-ios"
export SHERPA_ONNXRUNTIME_LIB_DIR="$ROOT/ort-ios/onnxruntime.xcframework/ios-arm64"
export SHERPA_ONNXRUNTIME_INCLUDE_DIR="$SHERPA_ONNXRUNTIME_LIB_DIR/onnxruntime.framework/Headers"
cmake -S "$ROOT/sherpa-onnx" -B "$ROOT/ios-build" \
  -DCMAKE_TOOLCHAIN_FILE="$ROOT/sherpa-onnx/toolchains/ios.toolchain.cmake" \
  -DPLATFORM=OS64 -DENABLE_BITCODE=0 -DENABLE_ARC=1 -DENABLE_VISIBILITY=0 \
  -DDEPLOYMENT_TARGET=17.0 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF \
  -DSHERPA_ONNX_ENABLE_TTS=OFF -DSHERPA_ONNX_ENABLE_PYTHON=OFF \
  -DSHERPA_ONNX_ENABLE_BINARY=OFF -DSHERPA_ONNX_ENABLE_TESTS=OFF \
  -DSHERPA_ONNX_ENABLE_CHECK=OFF -DSHERPA_ONNX_ENABLE_PORTAUDIO=OFF \
  -DSHERPA_ONNX_ENABLE_JNI=OFF -DSHERPA_ONNX_ENABLE_C_API=ON \
  -DSHERPA_ONNX_ENABLE_WEBSOCKET=OFF -DSHERPA_ONNX_BUILD_C_API_EXAMPLES=OFF \
  2>&1 | tee "$ROOT/configure.log"
cmake --build "$ROOT/ios-build" --target sherpa-onnx-c-api -j 4 2>&1 | tee "$ROOT/build.log"
# Preserve full upstream notices, not only license labels. Source dependencies were
# fetched with the exact hashes in pinned sherpa CMake; no local modifications.
for name in LICENSE ThirdPartyNotices.txt; do
  curl --fail --location --max-time 30 --output "$ROOT/onnxruntime-$name" \
    "https://raw.githubusercontent.com/microsoft/onnxruntime/v1.28.2/$name"
done
python3 - <<'PY'
import hashlib, os
from pathlib import Path
root = Path(os.environ['ROOT'])
files = [root/'sherpa-onnx/LICENSE', root/'onnxruntime-LICENSE', root/'onnxruntime-ThirdPartyNotices.txt']
for component, names in {
    'eigen': ['LICENSE', 'COPYING.APACHE', 'COPYING.BSD', 'COPYING.MINPACK', 'COPYING.MPL2', 'COPYING.README'],
    'hclust_cpp': ['LICENSE'], 'json': ['LICENSE.MIT'], 'kaldi_decoder': ['LICENSE'],
    'kaldi_native_fbank': ['LICENSE'], 'kaldifst': ['LICENSE'],
    'kissfft': ['COPYING', 'LICENSES/BSD-3-Clause'], 'openfst': ['COPYING'],
    'simple-sentencepiece': ['LICENSE'],
}.items():
    files += [root/f'ios-build/_deps/{component}-src'/name for name in names]
text = '''FireRedASR2-AED candidate runtime and model notices
Generated by scripts/build_firered_runtime.sh from unmodified pinned inputs.

FireRedASR2-AED model: Apache-2.0, FireRedTeam/Xiaohongshu.
Official model: https://huggingface.co/FireRedTeam/FireRedASR2-AED/tree/2304afed56eacfee6256dee5937ed22ffa0b64ec
ONNX conversion: Copyright 2026 Fangjun Kuang (Xiaomi Corp.), Apache-2.0.
https://github.com/csukuangfj/FireRedASR2S/tree/5febe49b840d976a52aaa8e50d5f49df14e550e8
sherpa-onnx 1.13.8: https://github.com/k2-fsa/sherpa-onnx/tree/a5b4a944c5186a68bcdc0ac3011e4c541781ac84
ONNX Runtime 1.28.2: https://github.com/microsoft/onnxruntime/tree/v1.28.2
Eigen 5.0.1 unmodified source (MPL-2.0): https://gitlab.com/libeigen/eigen/-/tree/5.0.1
Other unmodified dependency source URLs/hashes: sherpa-onnx cmake/ at the revision above.
No weights are included in the app bundle. Distribution remains separately gated.
'''
for path in files:
    value = path.read_text()
    if not value.strip(): raise ValueError(f'Empty notice: {path}')
    text += '\n\n' + str(path.relative_to(root)) + '\n\n' + value
(root/'FireRedNotices.txt').write_text(text)
libs = sorted((root/'ios-build/lib').glob('*.a'))
if len(libs) != 9: raise ValueError('Expected exactly nine device static libraries')
inputs = libs + [root/'ort-ios/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/onnxruntime', root/'FireRedNotices.txt']
with (root/'runtime-sha256.txt').open('w') as output:
    for path in inputs:
        with path.open('rb') as stream: digest = hashlib.file_digest(stream, 'sha256').hexdigest()
        output.write(f'{digest}  {path.relative_to(root)}\n')
print('PASS: pinned device runtime built; nine static libraries, ORT and complete selected notices retained. No app/model execution.')
PY
